#!/bin/bash
set -ev

sudo apt-get update
sudo apt-get install lua5.3 liblua5.3-dev luarocks doxygen yamllint clang-tidy-9 \
 libsdl2-dev libsdl2-mixer-dev libfreetype6-dev libwxgtk3.0-gtk3-dev \
 libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev 

sudo pip3 install codespell cmakelint

# Required for LDocGen
luarocks --local install lpeg
# Required for lua lint check
luarocks --local install luacheck
# Required for lua unit tests
luarocks --local install busted

# Build catch2
git clone --quiet https://github.com/catchorg/Catch2 --branch v2.13.2 --depth=1
cd Catch2
cmake . -Bbuild -DBUILD_TESTING=OFF
cd build
sudo make install
cd ../../
rm -rf Catch2
