#!/bin/bash
set -ev
# Get build dependencies
brew update > /dev/null
brew install homebrew/versions/lua53 ffmpeg freetype sdl2 wxwidgets
brew install sdl2_mixer --with-smpeg2
brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
ln -vf /usr/local/bin/luarocks-5.3 /usr/local/bin/luarocks
luarocks install lpeg
luarocks install luafilesystem
luarocks install luasocket
curl -fLsS https://patch-diff.githubusercontent.com/raw/diegonehab/luasocket/pull/69.diff | patch -bfN \
	--verbose /usr/local/share/lua/5.3/socket/http.lua
