#!/bin/bash
set -ev
# Get build dependencies
brew update > /dev/null
brew install lua53 ffmpeg freetype sdl2
brew install sdl2_mixer --with-smpeg2
brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
ln -vf /usr/local/bin/luarocks-5.3 /usr/local/bin/luarocks
luarocks install lpeg
luarocks install luafilesystem
